"""
영상 씬 데이터 — 'AI는 평균을 주고, 책은 깊이를 준다'
논리·인사이트형 톤, 10분(약 600초), 38개 씬

각 씬:
  id        : 씬 번호
  part      : HOOK / INTRO / BODY1~5 / 실전 / CTA / 전환
  duration  : 목표 노출 시간(초). 실제 길이는 TTS 합성 후 audio_duration로 덮어씀
  title     : 좌상단 작은 라벨
  big1/big2 : 화면 중앙 큰 자막 (키네틱 타이포)
  caption   : 화면 하단 자막(요약)
  narration : TTS로 읽을 문장
  accent    : 강조색 키 ('gold' | 'green' | 'red' | 'white')
"""

SCENES = [
    # ── HOOK 0:00–0:30 ──────────────────────────────────────────────
    dict(id=1, part="HOOK", duration=8,
         title="AI 시대,",
         big1="왜 책을 읽어야 할까",
         big2="",
         caption="",
         narration="솔직히, 요즘 책을 굳이 읽어야 하나 싶죠.",
         accent="gold"),
    dict(id=2, part="HOOK", duration=10,
         title="ChatGPT 한 줄이면 5분",
         big1="요약해줘",
         big2="끝.",
         caption="이 책 요약해줘 한 마디면 5분이면 끝나는 시대",
         narration="ChatGPT한테 이 책 요약해줘 한 줄이면, 5분이면 끝나는 시대잖아요.",
         accent="red"),
    dict(id=3, part="HOOK", duration=12,
         title="그런데 이상한 게 있습니다",
         big1="AI를 가장 잘 쓰는",
         big2="사람들은…",
         caption="",
         narration="그런데 이상한 게 있습니다. AI를 가장 많이, 가장 잘 쓰는 사람들. 빌 게이츠, 일론 머스크, 사티아 나델라.",
         accent="gold"),
    dict(id=4, part="HOOK", duration=12,
         title="더 많이 읽고 있습니다",
         big1="더 적게가 아니라",
         big2="더 많이",
         caption="이 사람들이 요즘 더 많이 한다는 건 — 독서",
         narration="이 사람들이 요즘 더 많이 한다는 게 뭔지 아세요? 독서입니다. 더 적게도 아니고, 더 많이.",
         accent="green"),

    # ── INTRO 0:30–1:10 ────────────────────────────────────────────
    dict(id=5, part="INTRO", duration=18,
         title="오늘의 한 문장",
         big1="AI는 평균을 주고",
         big2="책은 깊이를 준다",
         caption="이 영상의 모든 메시지는 이 한 문장에 담깁니다",
         narration="오늘 영상의 핵심을 한 문장으로 요약하면 이겁니다. AI는 평균을 주고, 책은 깊이를 준다.",
         accent="gold"),
    dict(id=6, part="INTRO", duration=12,
         title="오늘 다룰 것",
         big1="이유 5가지 + 실전 3가지",
         big2="",
         caption="끝까지 보시면 AI 시대 독서법 3가지를 드립니다",
         narration="이 한 문장이 왜 진짜인지 다섯 가지 이유로 풀어드리고, 마지막에 AI 시대 독서법 세 가지까지 정리해드릴게요.",
         accent="white"),

    # ── BODY 1 (메인) 1:10–3:30 ─────────────────────────────────────
    dict(id=7, part="BODY1", duration=12,
         title="이유 1",
         big1="AI는 평균을 준다",
         big2="",
         caption="첫 번째 이유 — 가장 중요한 이유",
         narration="첫 번째 이유. AI는 평균을 줍니다. 이게 무슨 말이냐면.",
         accent="gold"),
    dict(id=8, part="BODY1", duration=18,
         title="AI 답변의 정체",
         big1="수억 개 텍스트의",
         big2="통계적 중간값",
         caption="ChatGPT가 내놓는 답은 보편적·평균적인 답",
         narration="ChatGPT가 내놓는 답변은, 수억 개의 텍스트를 학습한 결과 중에서 가장 통계적으로 평균에 가까운 답입니다. 다수가 동의할 만한, 가장 보편적인 답이라는 뜻이에요.",
         accent="red"),
    dict(id=9, part="BODY1", duration=16,
         title="안전하지만",
         big1="모두가 같은",
         big2="평균값을 받는다",
         caption="모두가 같은 AI에게 묻고, 같은 답을 받는 시대",
         narration="그래서 안전하고, 그래서 무난합니다. 그런데 동시에, 남들과 똑같다는 뜻이기도 해요. 모두가 같은 AI에게 묻고, 모두가 같은 평균값을 받습니다.",
         accent="red"),
    dict(id=10, part="BODY1", duration=18,
         title="그럼 책은?",
         big1="한 사람의 10년이",
         big2="응축된 비대칭 정보",
         caption="평균이 아닌, 한쪽으로 치우친 깊이",
         narration="그럼 책은 어떨까요? 책은, 한 명의 저자가 5년, 10년, 길게는 평생을 한 주제에 파고들어서 나온 결과물입니다. 평균이 아니에요. 한쪽으로 치우친, 비대칭 정보예요.",
         accent="gold"),
    dict(id=11, part="BODY1", duration=15,
         title="비대칭이라는 건",
         big1="남들이 모르는",
         big2="나만의 깊이",
         caption="평균에서 벗어난다 = 비대칭을 확보한다",
         narration="비대칭이라는 건, 남들은 모르는데 나만 아는 영역이 생긴다는 뜻입니다. 평균에서 벗어난다는 건, 결국 어딘가에서 비대칭을 확보했다는 거예요.",
         accent="green"),
    dict(id=12, part="BODY1", duration=15,
         title="그 출발점은",
         big1="거의 항상",
         big2="책이다",
         caption="유튜브 요약본이 아닌, 한 사람의 사고가 담긴 한 권",
         narration="그리고 그 비대칭의 출발점은 거의 항상 책입니다. 유튜브 요약본도 아니고, 블로그 정리글도 아니고, 한 사람의 사고가 처음부터 끝까지 한 흐름으로 정리된 책이에요.",
         accent="gold"),
    dict(id=13, part="BODY1", duration=15,
         title="AI에게만 물으면",
         big1="남들과 같은",
         big2="출발선",
         caption="같은 AI를 써도 결과가 갈리는 이유",
         narration="AI에게만 물으면 남들과 같은 출발선에 서고, 책을 읽으면 남들과 다른 출발선에 섭니다. 같은 AI를 써도 그 결과가 달라지는 이유가 여기 있어요.",
         accent="red"),
    dict(id=14, part="BODY1", duration=16,
         title="정리하면",
         big1="AI는 평균을",
         big2="책은 깊이를",
         caption="이 한 문장을 머리에 박고 다음으로",
         narration="정리하면, AI는 평균을 주고 책은 깊이를 줍니다. 이걸 머리에 박고, 다음으로 가시죠.",
         accent="gold"),
    dict(id=15, part="전환", duration=8,
         title="두 번째 이유",
         big1="더 중요해요",
         big2="",
         caption="",
         narration="여기까지가 첫 번째 이유였고요. 두 번째가 더 중요해요.",
         accent="white"),

    # ── BODY 2 3:30–4:50 ───────────────────────────────────────────
    dict(id=16, part="BODY2", duration=16,
         title="이유 2",
         big1="좋은 프롬프트는",
         big2="사전지식에서 나온다",
         caption="AI 활용력 = 좋은 질문을 던지는 능력",
         narration="두 번째 이유. AI에게 좋은 답을 받는 능력은 결국 좋은 질문을 던지는 능력입니다. 그리고 좋은 질문은, 사전지식에서 나옵니다.",
         accent="gold"),
    dict(id=17, part="BODY2", duration=15,
         title="같은 주제, 다른 결과",
         big1="어휘 · 맥락 · 구조",
         big2="",
         caption="이 세 가지가 갖춰진 사람의 질문은 다르다",
         narration="같은 주제로 AI에게 물어도, 어휘가 풍부하고 맥락을 알고 구조를 이해하는 사람이 던지는 질문은 결과 자체가 달라집니다.",
         accent="green"),
    dict(id=18, part="BODY2", duration=16,
         title="그 어휘와 맥락은",
         big1="긴 흐름을 따라가본",
         big2="경험에서 자란다",
         caption="짧은 영상이 아니라, 긴 흐름의 책에서",
         narration="그럼 그 어휘와 맥락은 어디서 길러질까요? 짧은 영상 십 초짜리에서? 알고리즘이 골라준 피드에서? 아니에요. 길게 한 흐름을 따라가본 경험에서, 즉 책에서 길러집니다.",
         accent="gold"),
    dict(id=19, part="BODY2", duration=14,
         title="그래서 결론은",
         big1="책은 AI의 반대말이 아니라",
         big2="AI의 입력을 키우는 도구",
         caption="",
         narration="AI를 잘 쓴다는 건 결국 입력을 잘 만든다는 거고, 입력을 잘 만드는 능력은 독서로 자라요. 책은 더 이상 AI의 반대말이 아니라, AI의 입력을 키우는 도구입니다.",
         accent="green"),
    dict(id=20, part="전환", duration=7,
         title="다음이 진짜 핵심",
         big1="이 다음이",
         big2="진짜 핵심",
         caption="",
         narration="이게 와닿으셨다면, 다음 게 진짜 핵심입니다.",
         accent="white"),

    # ── BODY 3 4:50–5:50 ───────────────────────────────────────────
    dict(id=21, part="BODY3", duration=15,
         title="이유 3",
         big1="독해력 = AI 시대의",
         big2="새로운 문해력",
         caption="가장 저평가된 능력",
         narration="세 번째 이유. AI 시대에 가장 저평가된 능력이 뭔지 아세요? 독해력입니다.",
         accent="gold"),
    dict(id=22, part="BODY3", duration=18,
         title="AI는 답을 길게 줍니다",
         big1="수십 줄, 수십 페이지",
         big2="",
         caption="그걸 빠르게 읽고 판단하는 힘 = 독해력",
         narration="AI는 답을 짧게 안 줘요. 수십 줄, 길게는 수십 페이지짜리 보고서를 쏟아냅니다. 그걸 빠르게 읽고, 어디가 맞고 어디가 틀린지 판단할 수 있는 힘. 이게 곧 독해력이에요.",
         accent="red"),
    dict(id=23, part="BODY3", duration=15,
         title="병목은 여기에 있습니다",
         big1="못 읽으면",
         big2="못 쓴다",
         caption="AI 사용의 마지막 병목 = 우리의 독해 근육",
         narration="긴 글을 못 읽는 사람은, AI가 좋은 답을 줘도 못 씁니다. 무엇이 핵심인지 못 잡으니까요. AI 사용의 마지막 병목은 결국 우리의 독해 근육이에요.",
         accent="red"),
    dict(id=24, part="BODY3", duration=12,
         title="그 근육은",
         big1="오직",
         big2="책에서",
         caption="30분 한 흐름을 따라가는 책 읽기",
         narration="그리고 그 근육은, 30분, 한 시간 한 흐름을 따라가는 책 읽기에서만 길러집니다.",
         accent="green"),

    # ── BODY 4 5:50–6:55 ───────────────────────────────────────────
    dict(id=25, part="BODY4", duration=18,
         title="이유 4",
         big1="AI는 트렌드를 알고",
         big2="책은 본질을 안다",
         caption="100년 검증된 통찰은 책에 있다",
         narration="네 번째. AI는 트렌드를 잘 압니다. 학습 데이터가 최근 인터넷이니까요. 그런데 100년, 1000년 검증된 통찰은요? 그건 책에 있어요.",
         accent="gold"),
    dict(id=26, part="BODY4", duration=15,
         title="변하는 것 vs 변하지 않는 것",
         big1="본질은",
         big2="잘 변하지 않는다",
         caption="사람의 본성, 조직의 작동, 돈의 흐름",
         narration="사람의 본성, 조직의 작동, 돈의 흐름, 인간이 무엇에 움직이는가. 이런 본질은 잘 안 변합니다. 그래서 100년 전 고전이 지금도 통하는 거예요.",
         accent="white"),
    dict(id=27, part="BODY4", duration=15,
         title="똑똑한 전략",
         big1="트렌드는 AI에서",
         big2="본질은 책에서",
         caption="변하지 않는 것을 잡고 변하는 것을 다룬다",
         narration="그래서 똑똑한 전략은 이거예요. 트렌드는 AI에서, 본질은 책에서. 변하지 않는 걸 잡고 있어야, 변하는 걸 다룰 수 있습니다.",
         accent="green"),
    dict(id=28, part="전환", duration=8,
         title="다섯 번째",
         big1="가장 현실적인",
         big2="다섯 번째 이유",
         caption="",
         narration="그리고 어쩌면 가장 현실적인 다섯 번째 이유.",
         accent="white"),

    # ── BODY 5 6:55–7:55 ───────────────────────────────────────────
    dict(id=29, part="BODY5", duration=18,
         title="이유 5",
         big1="집중력은",
         big2="이제 자산이다",
         caption="평균 8초까지 떨어진 집중 시간",
         narration="집중력이 자산이 되는 시대입니다. 숏폼, 알림, AI 챗으로 우리 집중 시간은 점점 짧아지고 있어요. 평균 8초라는 통계까지 나오고 있죠.",
         accent="gold"),
    dict(id=30, part="BODY5", duration=20,
         title="역설적으로",
         big1="30분을 끝까지",
         big2="따라가는 능력 = 희소",
         caption="영화도 짧고, 유튜브도 짧고, AI도 스크롤로 끊긴다",
         narration="그래서 역설적으로, 30분, 한 시간 한 가지 흐름을 끝까지 따라갈 수 있는 능력 자체가 희소해졌습니다. 그리고 이걸 훈련할 수 있는 거의 유일한 도구가 책이에요. 영화도 짧고, 유튜브도 짧고, ChatGPT 답변도 스크롤로 끊깁니다.",
         accent="red"),
    dict(id=31, part="BODY5", duration=14,
         title="책 30분",
         big1="두뇌의 헬스",
         big2="",
         caption="가장 비싸지는 자산을, 가장 싼 도구로 매일 쌓는다",
         narration="책 30분은 두뇌의 헬스입니다. AI 시대에 점점 더 비싸지는 자산을, 가장 싼 도구로 매일 쌓는 거예요.",
         accent="green"),

    # ── 실전 7:55–9:15 ────────────────────────────────────────────
    dict(id=32, part="실전", duration=12,
         title="실전 정리",
         big1="AI 시대 독서법",
         big2="3가지",
         caption="",
         narration="자, 그러면 도대체 어떻게 읽어야 할까요? 실전 세 가지로 정리해드릴게요.",
         accent="gold"),
    dict(id=33, part="실전", duration=20,
         title="1",
         big1="AI에게 먼저",
         big2="요약시키지 마라",
         caption="순서를 바꾸면 평생 평균값 안에 갇힌다",
         narration="첫째, AI에게 먼저 요약시키지 마세요. 일단 내가 먼저 한 챕터라도 직접 읽고, 내 머리로 핵심을 잡은 다음 AI에게 검증시키는 순서가 맞아요. 순서를 바꾸면, 평생 평균값 안에 갇힙니다.",
         accent="red"),
    dict(id=34, part="실전", duration=18,
         title="2",
         big1="이해한 게 맞나",
         big2="AI에게 검증",
         caption="내가 먼저 정리하고 AI가 보완한다",
         narration="둘째, 챕터 끝마다 AI에게 물으세요. 내가 이렇게 이해했는데 맞나? 내가 먼저 정리하고 AI가 보완하는 구조. 이게 사고를 깊게 만듭니다.",
         accent="green"),
    dict(id=35, part="실전", duration=20,
         title="3",
         big1="책 → 노트 → 프롬프트",
         big2="자산화",
         caption="1년 뒤 결과는 완전히 달라진다",
         narration="셋째, 책에서 얻은 핵심을 노트로 정리하고, 그걸 내 프롬프트로 자산화하세요. 같은 AI를 써도, 나만의 프롬프트 라이브러리가 쌓이는 사람과 안 쌓이는 사람의 결과는 1년 뒤 완전히 다릅니다.",
         accent="gold"),

    # ── CTA 9:15–10:00 ────────────────────────────────────────────
    dict(id=36, part="CTA", duration=14,
         title="다시 한 번",
         big1="AI는 평균을",
         big2="책은 깊이를",
         caption="평균에서 깊이로 가는 사람만 AI를 도구로 쓴다",
         narration="다시 한 번 정리하겠습니다. AI는 평균을 줍니다. 책은 깊이를 줍니다. 평균에서 깊이로 가는 사람만, AI를 도구로 쓸 수 있어요.",
         accent="gold"),
    dict(id=37, part="CTA", duration=20,
         title="질문은 하나",
         big1="도구로 쓸 것인가",
         big2="도구가 될 것인가",
         caption="그 깊이를 만드는 가장 검증된 방법은 — 책",
         narration="AI는 점점 더 똑똑해질 겁니다. 그건 막을 수 없어요. 그런데 그 AI를 도구로 쓰느냐, 도구가 되느냐를 결정하는 건, 결국 우리가 얼마나 깊게 생각할 수 있느냐예요. 그 깊이를 만드는 가장 검증된 방법이, 책입니다.",
         accent="green"),
    dict(id=38, part="CTA", duration=15,
         title="댓글 챌린지",
         big1="요즘 읽고 있는",
         big2="책 한 권",
         caption="구독하시면 다음 영상 — 독서 환경 세팅 편",
         narration="오늘 댓글에 한 가지만 적어주세요. 요즘 읽고 있는 책 한 권. 다음 영상에서 가장 흥미로운 책들을 모아 소개해드리겠습니다. 구독하고 기다려주세요.",
         accent="gold"),
]


def total_planned_duration():
    return sum(s["duration"] for s in SCENES)


if __name__ == "__main__":
    total = total_planned_duration()
    print(f"Scenes: {len(SCENES)}")
    print(f"Planned total: {total}s = {total//60}:{total%60:02d}")
    chars = sum(len(s["narration"]) for s in SCENES)
    print(f"Narration chars: {chars}")
    print(f"Implied speaking rate: {chars/total*60:.0f} chars/min")
